### ISSUE TITLE
class Jawalbsms not found

### ISSUE THREAD

**Issue by ramisohail** [abdualrhmanio/jawalbsms#2]
i am facing an issue class not found, please fix

**Comment by Alfulayt** [comment]
it looks like the problem from your local environment  
try to remove it and reinstall it

**Comment by ramisohail** [comment]
yes it's from my computer 

thanks man

**Comment by ramisohail** [comment]
still facing the issue , please advise

**Comment by ramisohail** [comment]
i fixed it by using php artisan route:clear & php artisan config:clear then composer install
